fhs:
	$(INSTALL) -d $(SYSROOT)/bin
	$(INSTALL) -d $(SYSROOT)/boot
	$(INSTALL) -d $(SYSROOT)/dev
	$(INSTALL) -d $(SYSROOT)/etc
	$(INSTALL) -d $(SYSROOT)/etc/opt
	$(INSTALL) -d $(SYSROOT)/home
	$(INSTALL) -d $(SYSROOT)/lib
	$(INSTALL) -d $(SYSROOT)/media
	$(INSTALL) -d $(SYSROOT)/mnt
	$(INSTALL) -d $(SYSROOT)/opt
	$(INSTALL) -d $(SYSROOT)/root
	$(INSTALL) -d $(SYSROOT)/run
	$(INSTALL) -d $(SYSROOT)/sbin
	$(INSTALL) -d $(SYSROOT)/srv
	$(INSTALL) -d $(SYSROOT)/tmp
	$(INSTALL) -d $(SYSROOT)/usr
	$(INSTALL) -d $(SYSROOT)/usr/bin
	$(INSTALL) -d $(SYSROOT)/usr/games
	$(INSTALL) -d $(SYSROOT)/usr/include
	$(INSTALL) -d $(SYSROOT)/usr/lib
	$(INSTALL) -d $(SYSROOT)/usr/libexec
	$(INSTALL) -d $(SYSROOT)/usr/local
	$(INSTALL) -d $(SYSROOT)/usr/local/bin
	$(INSTALL) -d $(SYSROOT)/usr/local/etc
	$(INSTALL) -d $(SYSROOT)/usr/local/games
	$(INSTALL) -d $(SYSROOT)/usr/local/include
	$(INSTALL) -d $(SYSROOT)/usr/local/lib
	$(INSTALL) -d $(SYSROOT)/usr/local/man
	$(INSTALL) -d $(SYSROOT)/usr/local/sbin
	$(INSTALL) -d $(SYSROOT)/usr/local/share
	$(INSTALL) -d $(SYSROOT)/usr/local/src
	$(INSTALL) -d $(SYSROOT)/usr/sbin
	$(INSTALL) -d $(SYSROOT)/usr/share
	$(INSTALL) -d $(SYSROOT)/usr/share/man
	$(INSTALL) -d $(SYSROOT)/usr/share/misc
	$(INSTALL) -d $(SYSROOT)/usr/src
	$(INSTALL) -d $(SYSROOT)/var
	$(INSTALL) -d $(SYSROOT)/var/cache
	$(INSTALL) -d $(SYSROOT)/var/lib
	$(INSTALL) -d $(SYSROOT)/var/lib/misc
	$(INSTALL) -d $(SYSROOT)/var/local
	$(INSTALL) -d $(SYSROOT)/var/lock
	$(INSTALL) -d $(SYSROOT)/var/log
	$(INSTALL) -d $(SYSROOT)/var/mail
	$(INSTALL) -d $(SYSROOT)/var/opt
	$(INSTALL) -d $(SYSROOT)/var/spool
	$(INSTALL) -d $(SYSROOT)/var/tmp
