fhs:
	install -d $(SYSROOT)/bin
	install -d $(SYSROOT)/boot
	install -d $(SYSROOT)/dev
	install -d $(SYSROOT)/etc
	install -d $(SYSROOT)/etc/opt
	install -d $(SYSROOT)/home
	install -d $(SYSROOT)/lib
	install -d $(SYSROOT)/media
	install -d $(SYSROOT)/mnt
	install -d $(SYSROOT)/opt
	install -d $(SYSROOT)/root
	install -d $(SYSROOT)/run
	install -d $(SYSROOT)/sbin
	install -d $(SYSROOT)/srv
	install -d $(SYSROOT)/tmp
	install -d $(SYSROOT)/usr
	install -d $(SYSROOT)/usr/bin
	install -d $(SYSROOT)/usr/games
	install -d $(SYSROOT)/usr/include
	install -d $(SYSROOT)/usr/lib
	install -d $(SYSROOT)/usr/libexec
	install -d $(SYSROOT)/usr/local
	install -d $(SYSROOT)/usr/local/bin
	install -d $(SYSROOT)/usr/local/etc
	install -d $(SYSROOT)/usr/local/games
	install -d $(SYSROOT)/usr/local/include
	install -d $(SYSROOT)/usr/local/lib
	install -d $(SYSROOT)/usr/local/man
	install -d $(SYSROOT)/usr/local/sbin
	install -d $(SYSROOT)/usr/local/share
	install -d $(SYSROOT)/usr/local/src
	install -d $(SYSROOT)/usr/sbin
	install -d $(SYSROOT)/usr/share
	install -d $(SYSROOT)/usr/share/man
	install -d $(SYSROOT)/usr/share/misc
	install -d $(SYSROOT)/usr/src
	install -d $(SYSROOT)/var
	install -d $(SYSROOT)/var/cache
	install -d $(SYSROOT)/var/lib
	install -d $(SYSROOT)/var/lib/misc
	install -d $(SYSROOT)/var/local
	install -d $(SYSROOT)/var/lock
	install -d $(SYSROOT)/var/log
	install -d $(SYSROOT)/var/mail
	install -d $(SYSROOT)/var/opt
	install -d $(SYSROOT)/var/spool
	install -d $(SYSROOT)/var/tmp
